version: "3"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      volumes:
          - ./app:/app
      ports:
          - "8000:8000"
    
    db:
      image: mysql:8.0.21
      ports:
          - "30000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
          - ./db:/docker-entrypoint-initdb.d/:ro