version: "3"

volumes:
    jenkins_home:

services:
  jenkins:
    build: .
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
      - 8000:8000